name: Preload profile stats

on: 
  schedule: 
    - cron: "* */12 * * *"

  workflow_dispatch: 

  push: 
    branches: 
      - master

jobs: 
  generate_stats: 
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: 
      - name: Fetch SVG's
        env: 
          stats_dark: https://github-readme-stats-nine-bice-31.vercel.app/api?username=kcajeel&hide_title=false&hide_rank=true&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=github_dark&locale=en&hide_border=true
          stats_light: https://github-readme-stats-nine-bice-31.vercel.app/api?username=kcajeel&hide_title=false&hide_rank=true&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=github_light&locale=en&hide_border=true
        run: |
          mkdir output
          wget "$stats_dark" -O output/stats_dark.svg
          wget "$stats_light" -O output/stats_light.svg
      
      - name: Check SVG Generation
        run: |
          ls output
          test -f output/stats_dark.svg
          test -f output/stats_light.svg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
            name: stats
            path: output

  generate_languages: 
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: 
      - name: Fetch SVG's
        env: 
          languages_dark: https://github-readme-stats-nine-bice-31.vercel.app/api/top-langs?username=kcajeel&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=6&theme=github_dark&hide_border=true
          languages_light: https://github-readme-stats-nine-bice-31.vercel.app/api/top-langs?username=kcajeel&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=6&theme=github_light&hide_border=true
        run: |
          mkdir output
          wget "$languages_dark" -O output/languages_dark.svg
          wget "$languages_light" -O output/languages_light.svg
      
      - name: Check SVG Generation
        run: |
          ls output
          test -f output/languages_dark.svg
          test -f output/languages_light.svg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: languages
            path: output

  publish-branch:
    needs: [generate_stats, generate_languages]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps: 
        - name: Create Output Directory
          run: mkdir output

        - name: Collect Artifacts
          uses: actions/download-artifact@v4
          with: 
                path: output
      
        - name: Push Output to GitHub
          uses: crazy-max/ghaction-github-pages@v3.1.0
          with: 
            target_branch: output
            build_dir: output
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}